//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLandingTemplateRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseInformation
    {
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string BusinessHours { get; set; }
        public string SocialMedia { get; set; }
        public string Mision { get; set; }
        public string Vision { get; set; }
        public string Valores { get; set; }
        public string EmailOptional1 { get; set; }
        public string EmailOptional2 { get; set; }
        public byte[] Logo { get; set; }
        public int IdInfo { get; set; }
        public string PromotionalText1 { get; set; }
        public string PromotionalText2 { get; set; }
        public string PromotionalText3 { get; set; }
        public string PromotionalText4 { get; set; }
    }
}
