//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLandingTemplateRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCorp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceCorp()
        {
            this.ImageSources = new HashSet<ImageSources>();
        }
    
        public int ServiceId { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageSources> ImageSources { get; set; }
    }
}
